In [1]:
#List
nums = [25,12,36,95,14]
nums

[25, 12, 36, 95, 14]

In [2]:
nums[0]

25

In [4]:
nums[2:]

[36, 95, 14]

In [5]:
nums[-1]

14

In [7]:
values  = [9.5,"Neha",25]
values

[9.5, 'Neha', 25]

In [8]:
name = ["neha",'kavita',"runu"]
name

['neha', 'kavita', 'runu']

In [10]:
mil = [nums,name]
mil

[[25, 12, 36, 95, 14], ['neha', 'kavita', 'runu']]

In [11]:
#we can perform some operations using functions or methods
nums.append(45)
nums

[25, 12, 36, 95, 14, 45]

In [12]:
nums.insert(2,77)
nums

[25, 12, 77, 36, 95, 14, 45]

In [13]:
nums.remove(14)
nums

[25, 12, 77, 36, 95, 45]

In [15]:
nums.pop(1)
nums

[25, 36, 95, 45]

In [16]:
nums.pop()

45

In [24]:
del nums[2:]
nums

[25, 36]

In [25]:
nums.extend([29,12,14,36])
nums

[25, 36, 29, 12, 14, 36]

In [26]:
min(nums)


12

In [27]:
max(nums)

36

In [28]:
sum(nums)

152

In [29]:
nums.sort()
nums

[12, 14, 25, 29, 36, 36]

In [30]:
tup = (21,36,14,25)
tup

(21, 36, 14, 25)

In [31]:
tup[1]

36

In [32]:
#set
s = {23,34,56,23,45}
s

{23, 34, 45, 56}

In [33]:
s.add(21)
s

{21, 23, 34, 45, 56}

In [34]:
s.remove(56)
s

{21, 23, 34, 45}

In [35]:
s ={21,23,24,21} #don't support the duplicate values
s

{21, 23, 24}

In [36]:
# using help option 
help()



Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> topics

Here is a list of available topics.  Enter any topic name to get more help.

ASSERTION           DELETION            LOOPING             SHIFTING
ASSIGNMENT          DICTIONARIES        MAPPINGMETHODS      SLICINGS
ATTRIBUTEMETHODS    DICTIONARYLITERALS  MAPPINGS            SPECIALATTRIBUTES
ATTRIBUTES          DYNAMICFEATU

help> quit

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [37]:
#to know the certain address of variable
num = 5
id(num)

140710967817168

In [4]:
#array
#create an array
from array import*
arr = array('i',[])
n = int(input("Enter the length of the array"))
for i in range(n):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)
arr.pop(2)

Enter the length of the array5
Enter the next value3
Enter the next value2
Enter the next value4
Enter the next value5
Enter the next value6
array('i', [3, 2, 4, 5, 6])


4

In [7]:
from array import*
arr = array('i',[])
n = int(input("Enter the length of the array"))
for i in range(n):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)
arr.reverse()
print(arr)

Enter the length of the array4
Enter the next value6
Enter the next value7
Enter the next value4
Enter the next value5
array('i', [6, 7, 4, 5])
array('i', [5, 4, 7, 6])


In [21]:
import numpy as np
arr = array('i',[1,2,3,4,5])
print(arr)

array('i', [1, 2, 3, 4, 5])


In [28]:
import numpy as np
arr = np.linspace(0,15,16)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [30]:
arr = np.logspace(0,15,16)
print(arr)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15]


In [32]:
arr = np.arange(0,15,2)
print(arr)

[ 0  2  4  6  8 10 12 14]


In [36]:
arr =np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [37]:
arr =np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [50]:
arr1 = array('i',[1,2,3,4,5])
arr2 = array('i',[6,7,8,9,10])
arr3 =(np.sum(arr1 + arr2))

print(arr3)

55


In [46]:
print(np.sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [63]:
arr1 = array('i',[1,2,3,4,5])
arr2 = array('i',[6,7,8,9,10])
arr3 = arr1+arr2
print(arr3)

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


In [61]:
arr1 = array('i',[1,2,3,4,5])
arr1 = arr2
print(arr1)
print(arr2)

array('i', [6, 7, 8, 9, 10])
array('i', [6, 7, 8, 9, 10])


In [60]:
a = array('i', [1, 2, 3])
for i in range(len(a)):
    b = array('i', [4, 5, 6])
    print(a[i]+b[i],end=" ")

5 7 9 

In [66]:
arr = array('i',[100,200,30,10,993])
max = arr[0]
for x in arr:
    if max<x:
        max = x
print(max,"is the maximum")

993 is the maximum


In [68]:
arr1 = array('i',[[1,2,3],[4,5,6],[3,4,5]])
arr2 = array('i',[[1,4,5],[5,4,3],[4,7,8]])

if(arr1.shape[1] == arr2.shape[0]):
    arr3= []
    for i in range(arr1.shape[0]):

        for j in range(arr2.shape[1]):
            y = 0
            for k in range(arr2.shape[1]):
                x = arr1[i][k]*arr2[k][j];
                y = y+x
            arr3.append(y)
    m = matrix(arr3).reshape(1,3,3)
    print(m)
else:
    print("Array multiplication is not possible")

TypeError: an integer is required (got type list)

In [70]:
#defining function and calling
def add_sub(x,y):
    c = x+y
    d = x-y
    return c,d
result1,result2 = add_sub(5,4)
print(result1,result2)

9 1


In [4]:
a = 10

def some():
    a = 9
    x = globals()['a']
    print("in fun",a)
    globals()['a']=15
    
some() 

print("outside",a)
    

in fun 9
outside 15


In [3]:
def nam(lst1):
    
    letters = 0
    
    for i in range(len(lst1)):
        if lst1[i]>lst1[5]:
            letters+=1
            
        else:
             print("small name length")
                
        return letters
lst1 =['Amrita','Neha','chandrakat','tanusridas','maumita','unidhi','mitali']
    
letters = nam(lst1) 
print(letters)

small name length
0


In [4]:
def name(lst):
    lst2=[]
    count =0
    for i in lst:
        if len(i)>=5:
            lst2.append(i)
            count = count+1
        else:
            continue

    return lst2,count


lst=[]
for i in range (0,10):
    x=(input("Enter a name "))
    lst.append(x)
print(lst)

lst2,count=name(lst)
print ("Name greater than 5 letter or equals  ",lst2)
print ("Total number of person  ",count)

Enter a name indrani
Enter a name amit
Enter a name sunil
Enter a name prisha
Enter a name mohan
Enter a name chandrakant
Enter a name tanusri 
Enter a name madhu
Enter a name mohandas
Enter a name ramchandra
['indrani', 'amit', 'sunil', 'prisha', 'mohan', 'chandrakant', 'tanusri ', 'madhu', 'mohandas', 'ramchandra']
Name greater than 5 letter or equals   ['indrani', 'sunil', 'prisha', 'mohan', 'chandrakant', 'tanusri ', 'madhu', 'mohandas', 'ramchandra']
Total number of person   9


In [21]:
def fib(n):
   
    a = 0
    b = 1
    if n<=0:
        print("pass valid input!")
    
    elif n==1:
        
        print(a)
    else:
        print(a)
        print(b)
  
        for x in range(2,n):
            c=a+b
            a = b
            b = c
            print(c)


fib(10)



0
1
1
2
3
5
8
13
21
34


In [24]:
#Lambda Functions
def is_even(n):
    return n%2 == 0
nums = [3,2,6,8,4,6,9,12,10,7]
evens = list(filter(is_even,nums))
print(evens)
    

 

[2, 6, 8, 4, 6, 12, 10]


In [31]:
from functools import reduce
nums = [3,2,5,6,10,8,7,15,12]
even = list(filter(lambda n : n%2==0,nums))
doubles = list(map(lambda n : n*2,even))
add = reduce(lambda a,b:a+b,doubles)

print(even)
print(doubles)
print(add)


[2, 6, 10, 8, 12]
[4, 12, 20, 16, 24]
76


In [35]:
#decorator in python
def div(a,b):
    return a/b

def smart_div(func):
     
    def inner(a,b):
        if a<b:
            a,b = b,a
            return func(a,b)
    return inner
div = smart_div(div)
div(2,4)

2.0

In [42]:
def main():
    print("hello")
    print("users welcome")
    
    
#if__name__ == "__main__"
main()
    

hello
users welcome


In [6]:
class Circle:
    def area (self,r):
        a = 3.14*r**2
        return a
        print("Area of circle",a)
    
    def circumference(self,r):
         c = 2*3.14*r
         return c
         print("circumference of circle",c)
    
C1 = Circle()
#C1.area(7)
C1.circumference(5)

        
    

31.400000000000002

In [21]:
class Temperature:
    def fah(self,c):
        f = c*1.8000+32.00
        return f
        print(f)
 
    def cel(self,f):
         c = (f-32.00)/1.8000
         return c
         print(c)
            
      
t = Temperature()  
#t.fah(2)
t.cel(3)

    

-16.11111111111111

In [15]:
class Student():
  def __init__(self,name,roll):
    self.name = name
    self.roll= roll
  def display(self):
    print (self.name)
    print (self.roll)
  def setAge(self,age):
    self.age=15
    print(age)
  def setMarks(self,marks):
    self.marks = 100
    print(marks)
    
s1 = Student("neha",23)
s1.display()
s1.setAge(15)
s1.setMarks(100)

neha
23
15
100


In [17]:
class Time():

  def __init__(self, hours, mins):
    self.hours = hours
    self.mins = mins

  def addTime(t1, t2):
    t3 = Time(0,0)
    if t1.mins+t2.mins > 60:
      t3.hours = (t1.mins+t2.mins)/60
    t3.hours = t3.hours+t1.hours+t2.hours
    t3.mins = (t1.mins+t2.mins)-(((t1.mins+t2.mins)/60)*60)
    return t3

  def displayTime(self):
    print ("Time is",self.hours,"hours and",self.mins,"minutes.")

  def displayMinute(self):
    print (self.hours*60)+self.mins

a = Time(2,50)
b = Time(1,20)
c = Time.addTime(a,b)
c.displayTime()
c.displayMinute()


Time is 4.166666666666667 hours and 0.0 minutes.
250.00000000000003


TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'